#!/bin/bash

install_package() {
  echo "installing additional packages"
  sudo pacman -S bspwm kitty atuin starship nitrogen picom polybar rofi dunst gtk jgmenu --noconfirm
  sleep 2
  echo "installing ohmyzsh"
  sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
  sleep 2
  echo "installing nvim with aur"
  yay -S neovim-git --noconfirm
}

configuration_atuinsh() {
  echo "configure atuin on zsh prompt"
  echo 'eval "$(atuin init zsh)"' >> ~/.zshrc
}

configuration_starship() {
  echo "configure starship on zsh prompt"
  eval "$(starship init zsh)" >> ~/.zshrc
}

configuration_nvim() {
  git clone https://github.com/NvChad/starter ~/.config/nvim && nvim
}

configuration_all() {
  echo "copying bspwm configuration"
  rm -rf ~/.config/bspwm  ~/.config/kitty ~/.config/starship
  sudo cp * ~/.config/
}

if [[ "$1" == "--install" ]]; then
  install_package
  configuration_atuinsh
  configuration_starship
  configuration_nvim
  configuration_all
else
  echo "usage:"
  echo "--install: to install package"
fi
