; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |     https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|     z0mbi3.zk@protonmail.com
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../config/system.ini
include-file = modules.ini

[color]
bg = #141b1e
fg = #dadada

mbg = #232a2d
red = #e57474
pink = #c47fd5
purple = #c47fd5
blue = #67b0e8
blue-arch = #67b0e8
cyan = #6cbfbf
teal = #6cbfbf
green = #8ccf7e
lime = #8ccf7e
yellow = #e5c76b
amber = #e5c76b
orange = #e57474
brown = #b3b9b8
grey = #232a2d
indigo = #67b0e8
blue-gray = #dadada

[bar/hela]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 98%
height = 20

offset-x = 1%
offset-y = 5

background = ${color.bg}
foreground = ${color.fg}

radius = 0

line-size = 2
line-color = ${color.blue}

border-size = 10px
border-color = ${color.bg}

padding = 1

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "JetBrainsMono Nerd Font:size=9;2"
; Icons
font-1 = "Font Awesome 6 Free Solid:size=10;3"
font-2 = "Material Design Icons Desktop:size=11;3"
font-3 = "Material Design Icons Desktop:size=12;3"
;dpi = 96

;Modules availables but not active:
;	brightness xkeyboard
modules-left = launcher sep bspwm sep cpu_bar sep memory_bar sep filesystem sep
modules-center = 
modules-right = bluetooth sep battery sep network sep pulseaudio sep updates sep date sep tray sep power

separator =
dim-value = 1.0

;;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
